import type { Metadata } from "next";
import { JetBrains_Mono, Inter } from "next/font/google";
import "./globals.css";
import ClientRoot from "../components/ui/ClientRoot";
import SectionNavigator from "../components/ui/SectionNavigator";
import MobileSidebar from "../components/ui/MobileSidebar";
import { ThemeProvider } from "../components/ui/ThemeProvider";
import { UiPanelProvider } from "../components/ui/UiPanelContext";
import WelcomeModal from "../components/ui/WelcomeModal";
import Navbar from "../components/ui/Navbar";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NAV_LINKS = [
  { href: "#home", label: "Home" },
  { href: "#about", label: "About" },
  { href: "#skills", label: "Skills" },
  { href: "#experience", label: "Experience" },
  { href: "#projects", label: "Projects" },
  { href: "#medium-blogs", label: "Blogs" },
  { href: "#contact", label: "Contact" },
];


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} font-sans antialiased text-white`}
        style={{
          minHeight: "100vh",
          position: "relative",
          background: "linear-gradient(135deg, #23272f 0%, #353942 60%, #23272f 100%)"
        }}
      >
        <ThemeProvider>
          <UiPanelProvider>
            <WelcomeModal />
            <Navbar />
            <MobileSidebar />
            <ClientRoot>
              {children}
            </ClientRoot>
            <SectionNavigator />
          </UiPanelProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
