import type { Metadata } from "next";
import { JetBrains_Mono, Inter } from "next/font/google";
import "./globals.css";
import ClientRoot from "../components/ui/ClientRoot";
import SectionNavigator from "../components/ui/SectionNavigator";
import { ThemeProvider } from "../components/ui/ThemeProvider";
import ScrollbarToggleButton from "../components/ui/ScrollbarToggleButton";
import WelcomeModal from "../components/ui/WelcomeModal";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NAV_LINKS = [
  { href: "#home", label: "Home" },
  { href: "#about", label: "About" },
  { href: "#skills", label: "Skills" },
  { href: "#experience", label: "Experience" },
  { href: "#projects", label: "Projects" },
  { href: "#medium-blogs", label: "Blogs" },
  { href: "#contact", label: "Contact" },
];


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} font-sans antialiased text-white`}
        style={{
          minHeight: "100vh",
          position: "relative",
          background: "linear-gradient(135deg, #23272f 0%, #353942 60%, #23272f 100%)"
        }}
      >
        <ThemeProvider>
          <WelcomeModal />
          <ClientRoot>
            <SectionNavigator />
            {children}
          </ClientRoot>
          <ScrollbarToggleButton />
        </ThemeProvider>
      </body>
    </html>
  );
}
